# Copyright 2024 Robert Cronin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
auth0:
    callback_url: http://localhost:3000/api/callback
    redirect_url: http://localhost:5173
db:
    dsn: ENC[AES256_GCM,data:LCTOlVvBd18T31lvuig4RXnWwWc7yQt7QZwWOfEaTcqd76yf9PCSwu0Y6lUJq0HjS6eVl3Day8PcLyo2,iv:ASSDIlS2Au8TEs8Tuye8J7Q91VEyrCdc88kNUP78ud8=,tag:W+ADHyol5k/t03BMYIwRjg==,type:str]
redis:
    host: localhost
    port: 6379
    db: 0
session:
    secure: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-24T08:43:44Z"
    mac: ENC[AES256_GCM,data:6bfgert0/cfOwUR0COAjv9fncsgGH1Yb4eN0ioD+us4Qk/HaqrjZqGNZQZWhec3GvqeYAKMSUwP5h23Z/+LFhBm3/FHfUV8jgSIEuRO1GY5Vo+tUZ2fh+I0hCUjKsTFen2YfHIHT5ma0L8/xf3rPjPriMD1YWn5gPPC67ZqUYYo=,iv:eeSJZSwYVH62EaqmxkNehW2a2DT8EYdynYJ2mjWHj2Q=,tag:oeQ2VkCHtWqY6B+fBw7XPQ==,type:str]
    pgp:
        - created_at: "2024-06-24T08:43:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA6eqXQ0/huC+AQv/ekPObPIUs5TXdu7Qsvn8++I6KYhnP1bMAtJvvUNWPV+/
            vSGoKU9KrRntpcVOhknydj0vwY3tauLSr4qh8H6ef0FcjEDsch2De+b45OCurEjj
            4V+MtcEi7JJdU5PTxifF8kpwanSQbCo5xCy8O7bveCTW9yo/W+i1VgvcCVlIdiV/
            AUmgsUP6qiq4G8vvi5Bx6gZ/AebUJX03w6sva4Fdn9f+WY9tmh695+eAne7sEXsv
            mFaqahr9lgbXA1u5GSF0R42vPXCtOpqVlZQhuQJAO3FySQzPaXWsV6bQsEiFLoCq
            AQRgCcA59ZnCsdNoaQiimUgAYbYOViF0WxQ19AMwiT8lWWUKWeEL76oHcE/UNVY/
            NwMhrY1VOskC1dzOF6Corh4DrPQE8RnPs2I1yklpTHE6LfZpRqnGqOo3JiaPrD2Q
            NxIzIhOL0TnXRLIg8VIidbxprTi7nSR3QiXHgRzEirERh0TDMOus232wU85pLn5u
            lzAL/D4spBHP/Liy6McO0l4BGaBEx9Kg9QG2/xjhRxvwanfm9arS+yqGqt0BKK+b
            9Pkox+if906ZqV7aM9zmT4LtOFrfu7HM5/2iVoeOlKC9qN8Ul6bvDifzoG2+r3WF
            9EuWix2dHg9R67Xk67du
            =IhVd
            -----END PGP MESSAGE-----
          fp: 17D956D69F581977E848FC9FA228985D4ABDC074
    encrypted_regex: (?i)id|secret|domain|dsn
    version: 3.8.1
