# Copyright 2024 Robert Cronin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
auth0:
    callback_url: http://localhost:3000/api/callback
    redirect_uri: http://localhost:5173
db:
    dsn: ENC[AES256_GCM,data:zhcoczSfIXq6AxO9txRnGkGLES3umtBPQZv+/TqkewzzaILrE6/Cs2DBuDelM8zWOM9slwK+B/vVQtr6,iv:KRV37MVNf9L9aAWrt8j2+fmrHIS/3t/bhBGMUlbuWpY=,tag:lSLCy2q1VeHvdbuXd2/3Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-18T11:12:15Z"
    mac: ENC[AES256_GCM,data:ZhVTOV9ARct421crL7NfeqqPZZE9vq7y5AhCtweX6mzkBD4oFb/CW2cT2E4J5KefLhWDEVjG6Q9Y5W60nFhOvN7LrIWRt+C6039zhd5i/HMYc7UN+3Gk9GFI+FMQdn7+biQuAYzTyzyAJJ3d9V+mYzD0cPnpktsurJoz9t2BFUM=,iv:Mqwji7B1KFQgE7lzTi3wp0Sn14wJSu7BO99DwOO3Brg=,tag:rWnYm7IHsHfle4Dkkb+UgA==,type:str]
    pgp:
        - created_at: "2024-06-18T11:12:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA6eqXQ0/huC+AQv+OlyfCZ82e56oEj5io4cUn3kUXz4XwX2c5/fGUKx/NbvL
            KLBCTNjKnlsmKRMQrn20Mrv0JM6kfzJKfzHmw+AoAHs2adlDHpwbky08HUcRRoqG
            lQqJRgqL1KCvHqh5TgvjYp+5atc1Ft4n6rJBq8SM/YCNN5QZWILH41acAn4PRNjH
            X+sN8vqLMlrGaZFpNZEKfmwhD0m17Xhad9yts6+D5Xc869DbyVvmUH1Ldvd0RbQm
            JICq6Hm153gHgBwSddGFa5SvGXWJVJvKh1FW0oyufqhF0zq9AraXjSxeIKMxCBom
            PrD/6c/+fpKCw3N9ddFowxX0qg0pTzarmf9j708NN9H9wJolet1tepYfU2FY1PYg
            yt/57TRKkfVRVyY2mtVcFuTRoK49w4l1R8cFeeiqkUKGW+NMFpyze++pkuc4/Whr
            v1+K50vwgDf1fRsUMVWmgTnIpOqLR5IHHU2U0Y/dNg7yLP1ZZ8XWszIk9WPkLsuW
            8wxXkBKu8Keiriq9873A0lwBdAfGeJP1AyfqrmzDc5FydOrRVkHhg08i3ZOkEyET
            o/eRY7x1xN+QCGQEsYemhsYaJ6A4Z20Oitk4T5P6MwoBFVMz3i2IiyHU+bxYqcbK
            aIcWIVmL6T9hnlcNcw==
            =VqXY
            -----END PGP MESSAGE-----
          fp: 17D956D69F581977E848FC9FA228985D4ABDC074
    encrypted_regex: (?i)id|secret|domain|dsn
    version: 3.8.1
